import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import DocsLayout from "../docs-layout";
import { docsPages } from "../docs-content";

export function generateStaticParams() { return docsPages.map((page) => ({ slug: page.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const page = docsPages.find((item) => item.slug === slug); return page ? { title: `${page.title} — Documentation`, description: page.description } : {}; }
const request = `{"product_public_id":"prod_abc123456789012345678901","license_key":"IL-EXAMPLE-KEY","installation_id":"server-01","domain":"example.com"}`;
const response = `{"data":{"license_id":"uuid","product":"prod_abc123456789012345678901","plan":"Pro","status":"active","valid":true,"expires_at":"2027-01-01T00:00:00.000Z"},"error":null,"request_id":"uuid"}`;
function Code({ children }: { children: string }) { return <pre className="docs-code"><code>{children}</code></pre>; }
function Endpoint({ method, path }: { method: string; path: string }) { return <div className="docs-endpoint"><span>{method}</span><code>{path}</code></div>; }

function Content({ content }: { content: string }) {
  if (content === "intro") return <><p>IndoLicense gives software vendors a secure license key and activation layer. The API is tenant-aware, returns a consistent response envelope, and is designed to run from your application server.</p><h2>1. Create a product</h2><p>In the dashboard, create a Product and a Product License Plan. Copy the product&apos;s <code>product_public_id</code>; it is safe to include in your customer application.</p><h2>2. Choose a stable installation ID</h2><p>Use one stable identifier for each installation. It must be 8–160 characters and may contain letters, numbers, <code>.</code>, <code>_</code>, <code>:</code>, or <code>-</code>.</p><h2>3. Make your first request</h2><Endpoint method="POST" path="/api/v1/licenses/validate" /><Code>{`curl -X POST "$INDOLICENSE_URL/api/v1/licenses/validate" -H 'Content-Type: application/json' -d '${request}'`}</Code><h2>4. Handle the response</h2><p>Every public API response includes <code>data</code>, <code>error</code>, and <code>request_id</code>. Store the request ID in your application logs when troubleshooting.</p><Code>{response}</Code></>;
  if (content === "validate") return <><p>Validate checks the license status, product, plan, and expiration for an installation. It does not create an activation.</p><Endpoint method="POST" path="/api/v1/licenses/validate" /><h2>Request</h2><Code>{request}</Code><h2>Successful response</h2><Code>{response}</Code><h2>Recommended usage</h2><p>Run validation at application startup and periodically based on your product policy. You may cache a successful validation briefly; do not cache activation or deactivation responses.</p></>;
  if (content === "activate" || content === "deactivate") { const activate = content === "activate"; return <><p>{activate ? "Activate binds a license to an installation on first run. The same license and installation ID can be submitted again safely; repeated activation is idempotent." : "Deactivate releases an active installation when a customer uninstalls, migrates, or replaces a device."}</p><Endpoint method="POST" path={`/api/v1/licenses/${content}`} /><h2>Request</h2><Code>{request}</Code><h2>Behavior</h2><ul><li>Do not cache the response.</li><li>Use the same stable <code>installation_id</code> for the lifetime of an installation.</li><li>{activate ? "A new activation can fail with ACTIVATION_LIMIT_REACHED when the plan limit is full." : "Deactivation is scoped to the license and installation ID supplied in the request."}</li></ul></>; }
  if (content === "limits") return <><p>Public license endpoints use a per-product, per-action, per-IP window of 60 seconds.</p><div className="docs-table-wrap"><table className="docs-table"><thead><tr><th>Operation</th><th>Limit</th><th>Cache</th></tr></thead><tbody><tr><td>Validate</td><td>60 requests/minute</td><td>Short cache allowed</td></tr><tr><td>Activate</td><td>10 requests/minute</td><td>Do not cache</td></tr><tr><td>Deactivate</td><td>10 requests/minute</td><td>Do not cache</td></tr></tbody></table></div><h2>When throttled</h2><p>The API returns <code>429 RATE_LIMITED</code> and a <code>Retry-After</code> header. Wait for the specified number of seconds and retry with backoff. Never create an aggressive retry loop.</p></>;
  if (content === "errors") return <><p>Errors use the same envelope as successful responses, with <code>data: null</code> and a machine-readable error code.</p><Code>{`{"data":null,"error":{"code":"LICENSE_EXPIRED","message":"LICENSE EXPIRED"},"request_id":"uuid"}`}</Code><div className="docs-table-wrap"><table className="docs-table"><thead><tr><th>Code</th><th>HTTP</th><th>Recommended action</th></tr></thead><tbody>{[["INVALID_REQUEST","400","Fix the payload and validate input."],["LICENSE_NOT_FOUND","404","Check the product ID and license key."],["LICENSE_EXPIRED","409","Ask the customer to renew."],["LICENSE_SUSPENDED / LICENSE_REVOKED","409","Block protected features and contact the vendor."],["ACTIVATION_LIMIT_REACHED","409","Deactivate an old installation first."],["RATE_LIMITED","429","Wait for Retry-After before retrying."],["NETWORK_ERROR","5xx","Use limited cached validation only if your policy allows it."]].map(([code,http,action]) => <tr key={code}><td><code>{code}</code></td><td>{http}</td><td>{action}</td></tr>)}</tbody></table></div></>;
  if (content === "javascript") return <><p>The JavaScript/TypeScript reference SDK uses <code>fetch</code>, adds a 5-second timeout, and retries network errors, 408, 429, and 5xx responses up to two times.</p><Code>{`npm install @indolicense/javascript`}</Code><Code>{`import { IndoLicenseClient } from '@indolicense/javascript';\n\nconst client = new IndoLicenseClient(process.env.INDOLICENSE_URL!);\nconst result = await client.validate({\n  productPublicId: process.env.INDOLICENSE_PRODUCT_PUBLIC_ID!,\n  licenseKey: process.env.INDOLICENSE_LICENSE_KEY!,\n  installationId: 'server-01',\n  domain: 'example.com',\n});`}</Code><p><code>validate()</code> uses a 30-second in-memory cache by default. <code>activate()</code> and <code>deactivate()</code> are never cached. Errors are exposed as <code>IndoLicenseError</code> with error code, HTTP status, request ID, and retry-after seconds.</p></>;
  return <><p>The PHP reference SDK follows the same API contract and error model as the JavaScript SDK.</p><Code>{`composer require indolicense/php-sdk`}</Code><Code>{`use IndoLicense\\IndoLicenseClient;\nuse IndoLicense\\IndoLicenseException;\n\n$client = new IndoLicenseClient($_ENV['INDOLICENSE_URL']);\n$result = $client->validate(\n    $_ENV['INDOLICENSE_PRODUCT_PUBLIC_ID'],\n    $_ENV['INDOLICENSE_LICENSE_KEY'],\n    'server-01',\n    $_SERVER['HTTP_HOST'] ?? 'example.com',\n);`}</Code><p>Catch <code>IndoLicenseException</code> and log its error code and request ID. Never log the complete license key.</p></>;
}

export default async function DocsPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const page = docsPages.find((item) => item.slug === slug); if (!page) notFound(); return <DocsLayout currentSlug={page.slug}><div className="docs-breadcrumb"><Link href="/docs">Docs</Link><span>/</span>{page.group}</div><div className="docs-kicker">{page.group}</div><h1>{page.title}</h1><p className="docs-lead">{page.description}</p><div className="docs-rule" /><Content content={page.content} /></DocsLayout>; }
