"use client";

import Link from "next/link";
import { useState } from "react";

type Plan = { id: string; name: string; productId: string; productName: string; durationDays: number; activationLimit: number };
type LicenseItem = { id: string; keyPrefix: string; status: string; startsAt: string | Date; expiresAt: string | Date; activationLimit: number; product: string; plan: string; customerName: string | null; customerEmail: string | null; activationCount: number };
type Initial = { items: LicenseItem[]; nextOffset: number | null };

export default function LicensePanel({ organizationId, products, plans, initial, offset }: { organizationId: string; products: { id: string; name: string }[]; plans: Plan[]; initial: Initial; offset: number }) {
  const [licenses, setLicenses] = useState(initial); const [productId, setProductId] = useState(products[0]?.id ?? ""); const [planId, setPlanId] = useState(plans.find((plan) => plan.productId === productId)?.id ?? ""); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [newKey, setNewKey] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const availablePlans = plans.filter((plan) => plan.productId === productId);
  async function createLicense(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch(`/api/organizations/${organizationId}/licenses`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ product_id: productId, product_license_plan_id: planId, customer: { name: name || undefined, email: email || undefined } }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.code ?? "CREATE_FAILED"); setNewKey(result.data.licenseKey); setLicenses((current) => ({ ...current, items: [{ ...result.data.license, product: products.find((product) => product.id === productId)?.name ?? "", plan: availablePlans.find((plan) => plan.id === planId)?.name ?? "", customerName: result.data.customer.name, customerEmail: result.data.customer.email, activationCount: 0 }, ...current.items] })); setMessage("License berhasil dibuat. Simpan key ini sekarang karena tidak dapat dilihat ulang."); } catch (error) { setMessage(error instanceof Error ? error.message.replaceAll("_", " ") : "CREATE_FAILED"); } finally { setBusy(false); } }
  return <><section className="card"><div className="eyebrow">Generate license</div><h2>New customer license</h2><form className="license-form" onSubmit={createLicense}><label>Product<select value={productId} onChange={(event) => { setProductId(event.target.value); setPlanId(plans.find((plan) => plan.productId === event.target.value)?.id ?? ""); }} required>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>License plan<select value={planId} onChange={(event) => setPlanId(event.target.value)} required>{availablePlans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.activationLimit} activations · {plan.durationDays} days</option>)}</select></label><label>Customer name<input value={name} onChange={(event) => setName(event.target.value)} maxLength={160} /></label><label>Customer email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><button disabled={busy || !productId || !planId}>{busy ? "Creating…" : "Generate license"}</button></form>{newKey && <div className="license-key" role="status"><strong>{newKey}</strong><small>{message}</small></div>}{message && !newKey && <p className="error-message" role="alert">{message}</p>}</section><section className="card"><div className="eyebrow">License inventory</div><h2>Customer licenses</h2>{licenses.items.length === 0 ? <p>No licenses yet.</p> : <div className="table-wrap"><table><thead><tr><th>Key</th><th>Product / plan</th><th>Customer</th><th>Status</th><th>Activations</th><th>Expires</th></tr></thead><tbody>{licenses.items.map((license) => <tr key={license.id}><td><code>{license.keyPrefix}…</code></td><td>{license.product}<br /><small>{license.plan}</small></td><td>{license.customerName || "—"}<br /><small>{license.customerEmail || "—"}</small></td><td><span className="badge">{license.status}</span></td><td>{license.activationCount} / {license.activationLimit}</td><td>{new Date(license.expiresAt).toLocaleDateString("id-ID")}</td></tr>)}</tbody></table></div>}{(offset > 0 || licenses.nextOffset !== null) && <div className="pagination">{offset > 0 && <Link href={`?offset=${Math.max(0, offset - 20)}`}>← Previous</Link>}{licenses.nextOffset !== null && <Link href={`?offset=${licenses.nextOffset}`}>Next →</Link>}</div>}</section></>;
}
